{% set name = "RigolWFM" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/RigolWFM-{{ version }}.tar.gz
  sha256: fb61ab23d73ff414b39bfea9b077d94f28d032315df8a73070b18227b00a2894

build:
  entry_points:
    - wfmconvert = RigolWFM.wfmconvert:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=44
  run:
    - kaitaistruct
    - matplotlib-base
    - numpy
    - python >=3.8
    - requests

test:
  imports:
    - RigolWFM
  commands:
    - wfmconvert --version

about:
  home: https://github.com/scottprahl/RigolWFM
  summary: |
    A comprehensive resource for interpreting waveform ``.wmf`` files created
    by any Rigol oscilloscope.

  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.txt
  doc_url: https://rigolwfm.readthedocs.io/
  dev_url: https://github.com/scottprahl/rigolwfm/

extra:
  recipe-maintainers:
    - scottprahl
