{% set name = "RigolWFM" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 0e5b571022d086ec270366156a77402ffa575884bafe2e52119cc46f077c674d

build:
  entry_points:
    - wfmconvert = RigolWFM.wfmconvert:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=44
  run:
    - kaitaistruct
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - RigolWFM
  commands:
    - wfmconvert --version

about:
  home: https://github.com/scottprahl/RigolWFM
  summary: |
    A comprehensive resource for interpreting waveform ``.wmf`` files created
    by any Rigol oscilloscope.

  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.txt
  doc_url: https://rigolwfm.readthedocs.io/
  dev_url: https://github.com/scottprahl/rigolwfm/

extra:
  recipe-maintainers:
    - scottprahl
